import { useState, useCallback } from "react";
import { format, addDays, isToday, isTomorrow } from "date-fns";

export type ReminderType = 
  | "follow-up-signature" 
  | "no-activity"
  | "deadline-approaching"
  | "resend-transfer" 
  | "review-ai-suggestions"
  | "send-reminder" 
  | "custom";

export type NotificationMethod = "in-app" | "email" | "both";

export interface Reminder {
  id: string;
  type: ReminderType;
  text: string;
  documentName: string;
  documentType: "sign" | "transfer" | "ai-check" | "track";
  dueDate: Date | null;
  dueTime: string; // "09:00" format
  completed: boolean;
  completedAt?: Date;
  isSystemGenerated: boolean;
  note?: string;
  notificationMethod: NotificationMethod;
}

export interface NewReminderData {
  type: ReminderType;
  linkedDocument: string | null;
  dueDate: Date | null;
  dueTime: string;
  note: string;
  notificationMethod: NotificationMethod;
}

export interface SmartSuggestion {
  id: string;
  type: ReminderType;
  text: string;
  documentName: string;
  documentType: "sign" | "transfer" | "ai-check" | "track";
  reason: string;
  suggestedDate: Date | null;
}

const typeToText: Record<ReminderType, (docName: string) => string> = {
  "follow-up-signature": (doc) => `Follow up on signature for ${doc}`,
  "no-activity": (doc) => `No activity on ${doc}`,
  "deadline-approaching": (doc) => `Deadline approaching for ${doc}`,
  "resend-transfer": (doc) => `Resend transfer link for ${doc}`,
  "review-ai-suggestions": (doc) => `Review AI suggestions for ${doc}`,
  "send-reminder": (doc) => `Send reminder for ${doc}`,
  "custom": () => "Custom reminder",
};

export const reminderTypeLabels: Record<ReminderType, string> = {
  "follow-up-signature": "Follow up on signature",
  "no-activity": "No activity for X days",
  "deadline-approaching": "Deadline approaching",
  "resend-transfer": "Resend transfer link",
  "review-ai-suggestions": "Review AI suggestions",
  "send-reminder": "Send reminder",
  "custom": "Custom reminder",
};

// Mock initial reminders including system-generated ones
const initialReminders: Reminder[] = [
  {
    id: "1",
    type: "follow-up-signature",
    text: "Follow up on NDA signature",
    documentName: "NDA Agreement - Acme Corp",
    documentType: "sign",
    dueDate: new Date(),
    dueTime: "09:00",
    completed: false,
    isSystemGenerated: false,
    notificationMethod: "in-app",
  },
  {
    id: "2",
    type: "resend-transfer",
    text: "Resend transfer link",
    documentName: "Q4 Report.pdf",
    documentType: "transfer",
    dueDate: addDays(new Date(), 1),
    dueTime: "09:00",
    completed: false,
    isSystemGenerated: false,
    notificationMethod: "both",
  },
  {
    id: "3",
    type: "review-ai-suggestions",
    text: "Review AI suggestions",
    documentName: "Contract_v2.docx",
    documentType: "ai-check",
    dueDate: null,
    dueTime: "09:00",
    completed: false,
    isSystemGenerated: false,
    notificationMethod: "in-app",
  },
];

// Mock smart suggestions (would be generated by analyzing user behavior)
const mockSmartSuggestions: SmartSuggestion[] = [
  {
    id: "sug-1",
    type: "no-activity",
    text: "No signature activity for 3 days",
    documentName: "Service Agreement - TechCo",
    documentType: "sign",
    reason: "No activity detected in 3 days — consider following up",
    suggestedDate: addDays(new Date(), 1),
  },
  {
    id: "sug-2",
    type: "deadline-approaching",
    text: "Deadline in 48 hours",
    documentName: "Partnership Contract",
    documentType: "sign",
    reason: "Signing deadline approaches in 48 hours",
    suggestedDate: addDays(new Date(), 2),
  },
];

export function useReminders() {
  const [reminders, setReminders] = useState<Reminder[]>(initialReminders);
  const [showCompleted, setShowCompleted] = useState(false);
  const [smartSuggestions, setSmartSuggestions] = useState<SmartSuggestion[]>(mockSmartSuggestions);

  const pendingReminders = reminders.filter(r => !r.completed);
  const completedReminders = reminders.filter(r => r.completed);

  const addReminder = useCallback((data: NewReminderData) => {
    const newReminder: Reminder = {
      id: `user-${Date.now()}`,
      type: data.type,
      text: data.note || (data.linkedDocument ? typeToText[data.type](data.linkedDocument) : typeToText[data.type]("Document")),
      documentName: data.linkedDocument || "Unlinked",
      documentType: "sign", // Default, would be determined by actual document lookup
      dueDate: data.dueDate,
      dueTime: data.dueTime || "09:00",
      completed: false,
      isSystemGenerated: false,
      note: data.note || undefined,
      notificationMethod: data.notificationMethod,
    };
    setReminders(prev => [newReminder, ...prev]);
  }, []);

  const updateReminder = useCallback((id: string, data: Partial<NewReminderData>) => {
    setReminders(prev =>
      prev.map(r => {
        if (r.id !== id) return r;
        
        const updatedText = data.note || 
          (data.linkedDocument ? typeToText[data.type || r.type](data.linkedDocument) : r.text);
        
        return {
          ...r,
          type: data.type ?? r.type,
          text: updatedText,
          documentName: data.linkedDocument ?? r.documentName,
          dueDate: data.dueDate !== undefined ? data.dueDate : r.dueDate,
          dueTime: data.dueTime ?? r.dueTime,
          note: data.note ?? r.note,
          notificationMethod: data.notificationMethod ?? r.notificationMethod,
        };
      })
    );
  }, []);

  const completeReminder = useCallback((id: string) => {
    setReminders(prev => 
      prev.map(r => 
        r.id === id 
          ? { ...r, completed: true, completedAt: new Date() }
          : r
      )
    );
  }, []);

  const deleteReminder = useCallback((id: string) => {
    setReminders(prev => prev.filter(r => r.id !== id));
  }, []);

  const dismissSuggestion = useCallback((id: string) => {
    setSmartSuggestions(prev => prev.filter(s => s.id !== id));
  }, []);

  const acceptSuggestion = useCallback((suggestion: SmartSuggestion) => {
    const newReminder: Reminder = {
      id: `from-sug-${Date.now()}`,
      type: suggestion.type,
      text: suggestion.text,
      documentName: suggestion.documentName,
      documentType: suggestion.documentType,
      dueDate: suggestion.suggestedDate,
      dueTime: "09:00",
      completed: false,
      isSystemGenerated: false,
      notificationMethod: "in-app",
    };
    setReminders(prev => [newReminder, ...prev]);
    setSmartSuggestions(prev => prev.filter(s => s.id !== suggestion.id));
  }, []);

  const formatDueDate = useCallback((date: Date | null): string | null => {
    if (!date) return null;
    if (isToday(date)) return "Today";
    if (isTomorrow(date)) return "Tomorrow";
    return format(date, "MMM d");
  }, []);

  const formatDueDateTime = useCallback((date: Date | null, time: string): string | null => {
    if (!date) return null;
    const dateStr = isToday(date) ? "Today" : isTomorrow(date) ? "Tomorrow" : format(date, "MMM d");
    return `${dateStr} at ${time}`;
  }, []);

  const getNavigationPath = useCallback((reminder: Reminder): string => {
    switch (reminder.documentType) {
      case "sign":
        return `/track?tab=sign&document=${encodeURIComponent(reminder.documentName)}`;
      case "transfer":
        return `/transfer?document=${encodeURIComponent(reminder.documentName)}`;
      case "ai-check":
        return `/ai-check?document=${encodeURIComponent(reminder.documentName)}`;
      case "track":
        return `/track?document=${encodeURIComponent(reminder.documentName)}`;
      default:
        return "/";
    }
  }, []);

  return {
    reminders,
    pendingReminders,
    completedReminders,
    smartSuggestions,
    showCompleted,
    setShowCompleted,
    addReminder,
    updateReminder,
    completeReminder,
    deleteReminder,
    dismissSuggestion,
    acceptSuggestion,
    formatDueDate,
    formatDueDateTime,
    getNavigationPath,
  };
}